version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
  web: 
    build: ./client
    ports:
      - "85:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env